### ISSUE TITLE
4. Analysemodell Internetseite

### ISSUE THREAD

**Issue by majacal** [oliverhuckfeldt/pattframe#1]
ich mach dann das analysemodell .... 

wollen wir dann die repo hier nehmen um alle modelle zu mergen ? und die esa abzuschliessen ?

muessten wir nur alle contributor access bekommen auf die repo ?

**Comment by oliverhuckfeldt** [comment]
Hi Matthias,
Ok das ist gut. Wir haben jetzt schon gemacht: Reisebüro, Zeitungsverlag und Spedition. Du kannst dir ja noch ein anderes ausuchen. Wir sehen uns dann Sonntag. Wir wollten uns um 18 Uhr treffen. Schönes WE :)

Gruß Olli

**Comment by majacal** [comment]
alles klar 

wollen wir eine gemeinsame repo machen ? 

so können wir die files einfacher zusammenfügen ...

einfach git push git pull ... so hat man alle files immer parat
