### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by aspecialkey** [oliverhuckfeldt/pattframe#11]
Ich hab gelesen, dass man so vorgehen kann:
wenn die Sprites kreisähnlich sind, dann Mittelpunkte bestimmen und dann die Distanzen der Mittelpunkte beobachten. Bei uns im Prinzip immer nur Projektilmittelpunkt mit allen Invader mittelpunkten Distanz berechnen und vergleichen.

Andere Ideen?

**Comment by MatthiasHertel** [comment]
@aspecialkey test mention

**Comment by aspecialkey** [comment]
`ImageView.intersects(bounds);`

ist implementiert
