### ISSUE TITLE
1. Zwischenpraesentation abgabe freitag

### ISSUE THREAD

**Issue by majacal** [oliverhuckfeldt/pattframe#13]
> Zwischenpräsentation des Semesterprojekts
bitte, ladet eure Zwischenpräsentation hier hoch!

folie 8 zu ueberarbeiten uml diagramm ?

zustandsdiagramm

https://de.wikipedia.org/wiki/Zustandsdiagramm_(UML)

abgabe: (@matthiashertel)

praesentation google docs in pdf
jar file
alles in einem zipp

**Comment by aspecialkey** [comment]
watt isn da los??? es schleift ;)
du hast es aber noch auf dem schirm? (bzw jetzt ja wieder)
beste grüße

![grafik](https://cloud.githubusercontent.com/assets/22861526/21047150/8d9ce06e-be08-11e6-8eee-14eb5014ca9e.png)

**Comment by majacal** [comment]
sorry ich hatte die uhrzeit nich im blick ... ist oben 

00:00 is aber auch doof

**Comment by aspecialkey** [comment]
es sei dir verziehen ;)
stimmt, mit abgabezeit 0:00 uhr is blöde

schön, dass das jetz schonmal abgehakt is
