### ISSUE TITLE
tree (verzeichnisstruktur) bzw. skeleton

### ISSUE THREAD

**Issue by majacal** [oliverhuckfeldt/pattframe#14]
wie soll der tree unserer app aussehen ?

momentan sieht es so aus:

```bash
semesterprojekt/
├── artwork
│   ├── UI.svg
│   └── invaders-template.png
├── db
├── resources
│   ├── config
│   │   └── application.properties
│   └── images
│       ├── beuth-logo.png
│       └── invader.png
└── src
    └── org.blueberry.spaceinvaders
        └── SpaceInvaders.java
```

db wuerd ich den ganzen datenbank schnurz drinne haben .... 

oder resources /db lasst uns das hier mal klaeren.

ich glaub nach sonntag klassendiagramm sollten wir den stand den wir haben mal mit den master mergen und ein skeleton haben

**Comment by aspecialkey** [comment]
db würde ich so lassen
was haltet ihr davon in src nur java zu haben, fxml, css in die resourcen?

![grafik](https://cloud.githubusercontent.com/assets/22861526/21051834/4c578a36-be22-11e6-916c-2e029d72502d.png)

**Comment by majacal** [comment]
gehe ich mit

auch die theme ordner ... so muss man nur den einen root-path aendern wenn man sich an die ordnerkonvention innerhalb haelt 

top!

unter views die fxml dann ?

**Comment by aspecialkey** [comment]
würd ich mal so vorschlagen, für jeden screen eine fxml und die dann in den viewsordner

**Comment by aspecialkey** [comment]
├───resources
│   ├───assets
│   │   ├───theme1
│   │   │   ├───graphics
│   │   │   ├───sounds
│   │   │   └───stylesheets
│   │   ├───theme2
│   │   │   ├───graphics
│   │   │   ├───sounds
│   │   │   └───stylesheets
│   │   └───themeX
│   │       ├───graphics
│   │       ├───sounds
│   │       └───stylesheets
│   ├───config
│   ├───images
│   └───views
└───src
    └───org
        └───blueberry
            └───spaceinvaders

**Comment by aspecialkey** [comment]
#22 

semesterprojekt/

```
├── artwork
│   ├── UI.svg
│   └── invaders-template.png
(├── db (evtl andere repo ... weil es nur das webhook is))
(only db dump)
├── resources
│   ├── config
│   │   └── application.properties
│   └── theme1
│       ├── graphics
│       ├── sounds
│       └── stylesheets
│   └── theme2
│       ├── graphics
│       ├── sounds
│       └── stylesheets
│   └── theme3
│       ├── graphics
│       ├── sounds
│       └── stylesheets
│   └── views
│       └── welcomescreen.fxml
│       └── gameplayscreen.fxml
│       └── highscorescreen.fxml
└── src
|    └── org.blueberry.spaceinvaders
|        └── SpaceInvaders.java
└── lib
     └── mysql-connector-java-5.1.40-bin.jar

```
