### ISSUE TITLE
Klassendiagramm

### ISSUE THREAD

**Issue by majacal** [oliverhuckfeldt/pattframe#15]
bis sonntag wollen wir das klassendiagramm umsetzen ... 

hier erste ansaetze diskutieren ...

**Comment by aspecialkey** [comment]
![grafik](https://cloud.githubusercontent.com/assets/22861526/21081828/00df0620-bfcf-11e6-82c2-5133bb458ef4.png)

**Comment by majacal** [comment]
```bash

├── lib
│   └── mysql-connector-java-5.1.40-bin.jar
└── src
    └── highscore
        ├── Controller.java
        ├── DatabaseConnector.java
        ├── Highscore.java
        ├── Main.java
        └── highscore.fxml

```

![image](https://cloud.githubusercontent.com/assets/8426566/21088737/595bc0dc-c032-11e6-9cab-4f75ac33c948.png)

**Comment by majacal** [comment]
merge with multiple screens ...

![milestone0](https://cloud.githubusercontent.com/assets/8426566/21262539/1bae14ac-c392-11e6-9671-e26c96bc2a0e.png)
