### ISSUE TITLE
offline treffen

### ISSUE THREAD

**Issue by majacal** [oliverhuckfeldt/pattframe#20]
wie schauts aus kriegen wir mal eins hin ?

ich glaub waer ganz lustig ... und auch produktiv - pair programming oder xp

tendenziell immer do-so bei mir

schreibt doch mal wie ihr so zeit habt.

**Comment by aspecialkey** [comment]
ja gerne... macht mal konkrete Vorschläge!!
so mit bier? oder mit läppi?
oder mit bier und läppi???

**Comment by majacal** [comment]
also ich hab do-so eigentlich immer zeit ..

ja mit technik wuerd ich sagen so zum austausch ... und natuerlich :beers: 


hab ma nen doodle link gemacht zur termin findung:
http://doodle.com/poll/awra99fpyf2imr4h#table

**Comment by aspecialkey** [comment]
> hab ma nen doodle link gemacht zur termin findung:
http://doodle.com/poll/awra99fpyf2imr4h#table

hab nur mal n paar einträger gemacht, geht bei mir bestimmt noch mehr, abhängig von den anderen beiden

**Comment by aspecialkey** [comment]
jemand nen ortsvorschlag?

**Comment by majacal** [comment]
in uni naehe:

http://www.cafeschade.de/


"schuppke" gibs ja nich mehr
"auszeit" auch nimma

hmmm ... is halt die frage welcher kiez

**Comment by majacal** [comment]
**Donnerstag der 29.12.**
**Samstag 07.01.**

haben 3 treffer ...

**Comment by aspecialkey** [comment]
ja, da können wir doch schonmal den 29.12 festhalten!?
Uhrzeit?

**Comment by majacal** [comment]
ja ... 

17-18uhr halt ich fuer ne gute zeit

**Comment by majacal** [comment]
29.12 16Uhr cafe schade
