### ISSUE TITLE
offtopic / diskussion

### ISSUE THREAD

**Issue by majacal** [oliverhuckfeldt/pattframe#21]
hier offtopic ... diskussion ueber grundsaetze / herangehensweise ...

so nen laber - quatsch thread

**Comment by majacal** [comment]
so erster

keine ahnung wollt ma anfangen das nen bissle zu entzerren - entschuldigt wenn ihr mit emails bombardiert werdet / wurdet .. 

generell ... jeder issue kann bearbeitet (angepasst werden) oder geloescht werden ... 

nur halt um die grosse baustelle semesterprojekt die wir haben mal zu verschlanken ... in kleinere baustellen ... und dafuer nen kanal (diskussionsthread zu haben)

**Comment by aspecialkey** [comment]
ich finde es auch sinnvoll in kleine aufgaben zu zerlegen, danke, dass du dir die mühe gemacht hast

**Comment by majacal** [comment]
cooler screencast zu git:

https://www.youtube.com/watch?v=WS8whF0ZK-o&list=PLwAKR305CRO-fenwcN2-IC0rgaB6vaJgD

das sind zwar absolute basics ... aber hilfreich und nen guter anfang und im grunde mehr brauchen wir ja nicht ...

**Comment by aspecialkey** [comment]
@MatthiasHertel 
bist du jude?

ps: die frage kam nich von mir....

**Comment by aspecialkey** [comment]
achnee der hieß herzl
https://de.wikipedia.org/wiki/Theodor_Herzl

**Comment by majacal** [comment]
du typ 😂

Von meinem iPhone gesendet

**Comment by majacal** [comment]
> ps: die frage kam nich von mir....

achso von wem denn ?

**Comment by aspecialkey** [comment]
> achso von wem denn ?

du bist regelmäßiges gesprächsthema zwischen frauchen und mir

**Comment by aspecialkey** [comment]
Ich hab grad voll die Wahnvorstellungen:
Es gibt doch so alte Spiele, die immer mal wieder aufleben...
...und ich dachte, das könnte uns auch passieren
...wenn wir halt noch so zusatzfeatures einbauen, wie #25 hier
und wenn das mit den settings läuft und die themes
und mit dem webfrontend...wenn man da seine eigenen icons reinladen könnte (so halb selbsterstelltes spiel) is das doch voll der Renner ^^
...naja, ich bin nich so der spielexperte bzw hab gar keine Ahnung davon
Aber träumen is doch schön :)


ps: hab auch gelesen, dass man jvafx auch auf ios /android portieren kann....

**Comment by aspecialkey** [comment]
...ich glaub ich sitz zulange vorm rechner...

**Comment by aspecialkey** [comment]
> ...ich glaub ich sitz zulange vorm rechner...

das erinnert uns hieran: #20

**Comment by majacal** [comment]
> du bist regelmäßiges gesprächsthema zwischen frauchen und mir

ich weiss nicht ob mir das jetzt angst machen soll oder ich es lustig finden soll ^^

> Ich hab grad voll die Wahnvorstellungen:
Es gibt doch so alte Spiele, die immer mal wieder aufleben...
...und ich dachte, das könnte uns auch passieren
...wenn wir halt noch so zusatzfeatures einbauen, wie #25 hier
und wenn das mit den settings läuft und die themes
und mit dem webfrontend...wenn man da seine eigenen icons reinladen könnte (so halb selbsterstelltes spiel) is das doch voll der Renner ^^
...naja, ich bin nich so der spielexperte bzw hab gar keine Ahnung davon
Aber träumen is doch schön :)
> ps: hab auch gelesen, dass man jvafx auch auf ios /android portieren kann....

geht mir aehnlich ... ja das webfrontend zum ausrollen unseres spiels ... quasi RTM (release to marketing) column dann ... downloadbarer installer fuer die verschiedenen OS ... 

ja und mal schauen wie man in die appstores kommt ... google is da relativ einfach ... ios hat qualitaetskontrolle .. hab ma ne app mit ionic gemacht und die lokal aufm iphone gehabt mit der ganzen dev account scheisse (99$ pro jahr) usw usf ... aber ich glaub darueber machen wir uns gedanken wenn wir ne cooles spiel haben 

aehm ja maven build wuerd ich nehmen .. problem is bei der ganzen javascheisse is das man keen zerodeployment hat wie im HTTP .. also man den ganzen build murkss kram noch an der backe hat ... was auf der anderen seite ja cool ist .... aber bedeutet viel aufwand



> ...ich glaub ich sitz zulange vorm rechner...

hehe normal geht mir manchmal auch so ... aber ich glaub wir sollten fokussiert auf den milestone 1 sein ... aber traeumen darf man ja ...

**Comment by aspecialkey** [comment]
ey... ick bin den halben tag verzweifelt... und warum? weil ich einen int mit nem long addiert habe und nicht andersrum.... da kommt nichmal n fehler...... boh!!
naja, nächstmal ladt ich euch auf hangout dazu ein, dann könnt ihr mich dabei beobachten ;)

**Comment by majacal** [comment]
>  nächstmal ladt ich euch auf hangout dazu ein, dann könnt ihr mich dabei beobachten ;)

ja sehr gerne

**Comment by majacal** [comment]
mal etwas grundsaetzliches - wollen wir die repo private machen ?

momentan kann jeder unsere repo pullen ... also sich eine copy ziehen.

**Comment by aspecialkey** [comment]
hatte ich vorhin auch dran degacht, als über die db-credentials gesprochen wurde.
blöd wäre dann nur, dass isle dann nicht verfolgen könnte

**Comment by majacal** [comment]
ilse ist bestimmt auch bei github und man koennte sie als collaborator hinzufügen

Von meinem iPhone gesendet

**Comment by majacal** [comment]
900 pts :muscle: 

das muss erstmal eener knacken :joy:

**Comment by aspecialkey** [comment]
![bildschirmfoto 2016-12-22 um 23 30 59](https://cloud.githubusercontent.com/assets/22861526/21442546/c683e22e-c89e-11e6-8d60-651f073ebd02.png)

wer steht da ganz oben ???
bis ins level 723 gespielt…. und du brüstest dich??

**Comment by majacal** [comment]
:muscle: 
![image](https://cloud.githubusercontent.com/assets/8426566/21457073/ba2ac126-c92c-11e6-8c78-41f992708e95.png)

**Comment by majacal** [comment]
da laesste einmal dit frauchen spielen ^^

![image](https://cloud.githubusercontent.com/assets/8426566/21463095/ae9cc7d6-c964-11e6-939c-ef4783395b90.png)

**Comment by aspecialkey** [comment]
ey, lasst mich nicht eure application.properties sehen!!!!

Am 2016-12-23 23:08, schrieb Matthias Hertel:

> da laesste einmal dit frauchen spielen ^^ 
> 
> [1] 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1]
https://cloud.githubusercontent.com/assets/8426566/21463095/ae9cc7d6-c964-11e6-939c-ef4783395b90.png
[2]
https://github.com/MatthiasHertel/pattframe/issues/21#issuecomment-269050780
[3]

**Comment by majacal** [comment]
nee man die hatte einfach nur luck ... die hat zweimal dit misteryship getroffen voellig unklar ^^

**Comment by majacal** [comment]
![image](https://cloud.githubusercontent.com/assets/8426566/22395870/f20b202e-e54a-11e6-9310-31b528e86aea.png)
