### ISSUE TITLE
Fehlerbehandlung

### ISSUE THREAD

**Issue by aspecialkey** [oliverhuckfeldt/pattframe#23]
momentan gibts noch gar keine Fehlerbehandlung
-->muss noch gemacht werden

**Comment by majacal** [comment]
damit meinst du `try { } catch(exception e { e.doSth }` zweige ?

**Comment by aspecialkey** [comment]
jo
muss jetzt noch nicht, da sich der code noch regelmäßig verändert, wollts nurmal festhalten, dass wir`s nicht vergessen

**Comment by majacal** [comment]
jou haben wir auf dem schirm ... habs in der project seite in die `Release Candidate/Prerelease` column gezogen .... 

https://github.com/oliverhuckfeldt/pattframe/projects/1
