### ISSUE TITLE
Level

### ISSUE THREAD

**Issue by aspecialkey** [oliverhuckfeldt/pattframe#25]
wie funktioniert denn das mit den verschiedenen level?? werden die invader schneller, schießen sie öfter, werden es mehr????
jemand ne idee?
oder vorstellungen

wenn man das spiel geschafft hat, startet dann das nächste level automatisch?

**Comment by aspecialkey** [comment]
Ideen:

- Bunker könnten sich bewegen (wie invader, entgegengesetzt, random)

- Invader bewegen sich randommäßig

**Comment by majacal** [comment]
wollen wir leveling in milestone 1 mit reinziehen oder einen weiteren milestone dafuer haben ?

### einfacher aufwand:

- anzahl der invader 
`invader.line.count = 11`

- geschwindigkeit der invader
`ka welches application.properties`
- schussfrequenz der invader 
`ka welches application.properties`


### umfangreicher aufwand:

- invader bewegung randommaessig
- bunker bewegung


> wenn man das spiel geschafft hat, startet dann das nächste level automatisch?

wuerde das in #19 klaeren ... 
ob es einen loop auf dem gameplayscreen gibt ... wie nach spielende verfahren wird ... ob dann zwangslaeufig die highscore kommt ... usw usf

**Comment by aspecialkey** [comment]
> wollen wir leveling in milestone 1 mit reinziehen oder einen weiteren milestone dafuer haben ?

neuer

**Comment by markweigelt** [comment]
* Invader schneller
* Invader erst mit mehreren Schüssen killen
* Wegfallen der Bunker

**Comment by majacal** [comment]
> Invader erst mit mehreren Schüssen killen

find ich gut ... muesste man sich aber merken wie oft einer getroffen ist ... das ist umfangreicher oder @aspecialkey ? 

> Invader schneller
> Wegfallen der Bunker

sind "einfacher" umsetzbar .... 
habs unten mal mit aufgenommen ... 


### einfacher aufwand:

- anzahl der invader 
`invader.line.count = 11`

- geschwindigkeit der invader
`ka welches application.properties`
- schussfrequenz der invader 
`ka welches application.properties`

-  Wegfallen der Bunker (weniger bunker oder gar keine schutzbunker)

### umfangreicher aufwand:

- invader bewegung randommaessig
- bunker bewegung
- Invader erst mit mehreren Schüssen killen
