### ISSUE TITLE
InvaderGroup

### ISSUE THREAD

**Issue by aspecialkey** [oliverhuckfeldt/pattframe#27]
testNextGroupMove()
-->IndexOutOfBoundsException

nur manchmal, ich kann den Fehler nicht reproduzieren
falls ihr mal zum Testen kommt, achtet mal bitte darau und versucht den fehler zu reproduzieren

**Comment by majacal** [comment]
muss ich ma beobachten ... hatte ich bisher nicht ...

gehst du hart ueber die anzahl (welche sich veraendert) oder nimmst du foreach ?
