### ISSUE TITLE
GameplayView - Timer

### ISSUE THREAD

**Issue by aspecialkey** [oliverhuckfeldt/pattframe#28]

**Comment by majacal** [comment]
**im gameplay**

- [ ] Timer spielzeit an label binden

- [x] get auf score
- [ ] get auf bonusscore
- [ ] get auf gesamtscore
- [ ] get auf timer

**in der highscore: (dbschema anpassen)**

- [x] id
- [x] spielername
- [x] punkte
- [ ] bonuspunkte
- [ ] timer
- [ ] gesamtpunkte
- [x] created_at
- [x] updated_at
