### ISSUE TITLE
ollis austritt - was gibt es zu tun

### ISSUE THREAD

**Issue by majacal** [oliverhuckfeldt/pattframe#29]
- [x] repo umziehen
- [ ] moodle abgabe url zu unserer repo richtig setzen
- [x] isle darueber unterrichten ?
- [x] aufgaben von olli verteilen (screendesign uebernimmt mark)

**Comment by majacal** [comment]
@aspecialkey @markweigelt 

sollten wir ilse eine kurze email schreiben das olli ausgetreten ist ?

**Comment by aspecialkey** [comment]
ich denke, dass olli das selbst mit ilse klären sollte (wir ihm die möglichkeit dazu anbieten), ich würde es auch gut finden, wenn wir ne mailkopie erhalten, damit wir auch wissen was los ist, bzw, wir er es mitgeteilt hat.
wenn dies nicht zeitnah von olli geschieht, dann geben wir, ich würd vorschlagen so mitte nächster woche, ilse bescheid.
bzw kommt von uns, sofern olli dies nich schon mitteilt, noch ne mail bzgl repo.

...meine gadanken dazu
wie seht ihr es?

**Comment by majacal** [comment]
seh ich genauso ... 

wer schreibt olli das er ilse bescheid sagt und uns in den cc packt ?

**Comment by aspecialkey** [comment]
hiermal ein Anfang,
ändert gerne drin rum und sagt eure meinung, wäre schön, denk ich, wenn wir die mail heute noch raushauen:

Hallo Olli,
sofern Du Ilse noch nicht Bescheid gegeben hast, dass Du die Gruppe Blueberry verlassen hast, möchten wir Dich bitten, dies zeitnah zu erledigen. Damit wir auf dem Laufenden sind, setze uns bitte ins CC. Solltest Du Deinen Austritt schon verkündet haben, sei bitte so nett und lass uns die Mail dazu zukommen.
Wir wünschen Dir in Deinem weiteren Vorhaben viel Erfolg und erst einmal eine besinnliche Weihnachtszeit sowie vorab einen guten Rutsch, falls wir zwischendurch nix mehr von Dir hören .

Viele Grüße,
die restlichen blauen Beeren

**Comment by majacal** [comment]
ich find das kann man so abschiessen ... ich denke mark geht damit auch konform ? @markweigelt 

ansonsten das ja ne kleinigkeit ... schicken wir so ab ? dann haben wa das vom tisch


dann nur noch die urls aendern in moodle:

wobei ... github cached die ja alle

also 

https://github.com/oliverhuckfeldt/pattframe

bekommt halt nen redirect ... auf MatthiasHertel

**Comment by markweigelt** [comment]
Ja, hört sich gut an und kann von meiner Seite aus so rausgehen. Danke.

**Comment by aspecialkey** [comment]
du hattest doch olli aus dem repo rausgeschmissen, oder?!

![grafik](https://cloud.githubusercontent.com/assets/22861526/21296010/974df2fa-c561-11e6-9e0b-75669223c85e.png)

warum steht denn der oliver da noch drin??
und Mark nicht, is da was schief gelaufen?

**Comment by majacal** [comment]
weil diese statistik den gesammten zeitraum betrifft ... und er ja mal was commitet hatte

Von meinem iPhone gesendet

**Comment by aspecialkey** [comment]
aha
mensch, ich werd durch dich noch zum gitgeek
