### ISSUE TITLE
Invader gewinnen

### ISSUE THREAD

**Issue by aspecialkey** [oliverhuckfeldt/pattframe#31]
wenn die invader gewinnen, kann das spiel nicht neu gestartet werden

**Comment by aspecialkey** [comment]
bitte mal testen und bestätigen, dass es in einer früheren version auch schon der fall war, oder ob ich es jetzt verhauen hab

**Comment by majacal** [comment]
bin auf dem head ... 

und wenn die invader gewinnen kommt ein wechsel zur highscoreseite von der ich zurueck gehen kann auf die gameplayseite wo das spiel dann wieder ganz normal startet

**Comment by aspecialkey** [comment]
hääää, was hab ich gemacht???
hab meinen aktuellen stand gepusht, kannst du da auch ferststellen, dass der screenwechsel mit neuem spiel nicht klappt, wenn die invader gewinnen

**Comment by aspecialkey** [comment]
also wenn man mehr als null leben hat

**Comment by majacal** [comment]
jupp ... ich hatte noch 2leben und hab es aber nicht geschafft alle invader zu killen ... 

nun wollte ich nach wechsel automatischen wechsel auf highscorescreen zurueck und konnte nicht 

zwischenzweitlich hatte ich eine menge exception

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at org.blueberry.spaceinvaders.gameengine.Game$GameAnimationTimer.handle(Game.java:343)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$484(AnimationTimer.java:57)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by aspecialkey** [comment]
jaja, die exceptions ignorier mal(hat mit dem mysteryship zu tun), hab ich nur gepushed, um zu sehen, ob du das auch feststellst.
also in der alten version klappt das spiel neustarten und nun nicht, ja? hab ich so richtig verstanden?

**Comment by majacal** [comment]
jupp korrekt ... aber du kannst doch via:

`git checkout COMMITHASH`

selber zurueckspringen und das testen ... wir koennen dazu gern noch mal nen hangout machen ...

**Comment by aspecialkey** [comment]
hhmmmm ja.... wollte nur eigentlich den unfertigen stand nicht einchecken und hatte sichss, dass mir was verloren geht, wenn ich zurückgehe....
...und außerdem wollte ich eure langeweile füllen :p

**Comment by majacal** [comment]
hehe ... ja du kannst ja dein zwischenstand stashen ... 

git stash .

der punkt steht hierbei fuers current directory 


um es wieder ausm stash zu holen einfach 
git pop 1

glaub ist lifo oder fifo ... ziemlich simple

**Comment by aspecialkey** [comment]
ja, muss man sich mal trauen auszuprobieren!
...aber längst nich so simple, wie andere beauftragen ;)

**Comment by aspecialkey** [comment]
jetzt check ich gar nichts mehr:
also ich jetzt 
8de358a65dae376529c743a45ecd43a13e1c6f04 (test new commit matthias) ausgecheckt und hab da bei mir den fehler auch festgestellt....
wenn bei mir die invader die letzte bahn erreichen und ich noch am leben bin, dann wechselt er zum highscorescreen, wenn ich dann wieder auf gameplay gehe, springt er gleich wieder zu highscore (0 punkte)

**Comment by majacal** [comment]
bin gleich zuhause .... koennen dazu nen hangout machen .. is glaub ich einfacher!

**Comment by aspecialkey** [comment]
wann haben sie denn kurz zeit?

Am 2016-12-19 16:54, schrieb Matthias Hertel:

> bin gleich zuhause .... koennen dazu nen hangout machen .. is glaub ich einfacher! 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/MatthiasHertel/pattframe/issues/31#issuecomment-267999842
[2]

**Comment by majacal** [comment]
machen wir 20uhr ?

**Comment by aspecialkey** [comment]
okay

**Comment by aspecialkey** [comment]
ähm deine daten sind nun auf github öffentlich (letzter comment) -lösch mal
