### ISSUE TITLE
Datenbankserver + CRUD

### ISSUE THREAD

**Issue by majacal** [oliverhuckfeldt/pattframe#9]
- [x] datenbank server in die repo 

- [x] speicherung der daten aus einer javafx app ermoeglichen

- [ ] merge this with master ... ( have to wait for master skeleton until this is setuped use dummy inputs)

**Comment by majacal** [comment]
datenbank server aufgesetzt (homestead out of the box)
webapp (laravel 5.3) initialized to show the data in http context 

ok now build a javafx app to push data from it into db 
and then build a simple app to show them in a http context

**Comment by majacal** [comment]
momentaner zwischenstand:

hab jetzt ne app die kann ueber formularfelder name und punkte datensaetze aufnehmen
ausgeben updaten und deleten (update delete brauchen wir wenn dann spaeter fuer settings um die highscore zu reseten oder so nen quatsch)

db schema sieht wie folgt aus:

id autoincrement int
name string
punkte int
timestamps (created)
timestamps (updated)


auf dem datenbank server bzw webserver laeuft ne http app die genau dieselbe funktionalitaet im http abbildet (das nehmen wa mal so mit - war mit scaffolding kein aufwand )

**Comment by majacal** [comment]
@aspecialkey 

so also die simple crud existiert ... auch standalone lauffaehig ... 

im grunde brauchen wir fuer den 1. milestone nur create und read (er soll anhand der punkte ein insert fahren und in einem read die highscore anzeigen)

update und delete sind nice to have im settings screen (so dass man die highscore reseten kann oder einzelne beitraege bearbeiten kann)


aehm ich wuerd mir jetzt mal deinen stand ziehen du hast ja da schon nen label was die punkte zaehlt ...  und das alles verknuepfen ? so das eben die punkte in der db landen aber so richtig ein spielende gabs bei dir noch nicht oder ? mal schauen wie ich das mache ... oder ich warte damit und wir machen das spaeter und ich widme mich den bunker sprites jetzt mal siehe #16 

oder wollen wir dazu ma kurz ausserturnus maessig nen hangout einlegen ?

**Comment by aspecialkey** [comment]
ja insert und read reicht vollkommen, denk ich
...vielleicht mal irgendwann noch n delete

ich würde sagen, dass du dich mit meinem alten stand noch nicht rumschlagen brauchst....
...lieber erstmal die images, falls du bock hast...

hangout, vielleicht heute abend, falls ich noch bis dahin konstruktive werde

**Comment by majacal** [comment]
meld dich einfach wenn du bock hast ...

**Comment by aspecialkey** [comment]
mal ne anmerkung:
was hälst du denn davon, mit der webanwendung über einen anderen user, als der javaclient, auf die db reinzugehen? sonst könnte jeder, der an die jar kommt, sie entpackt, die db credentials findet, auch gleich mit schreibrechten zB auf die password_resets tabelle...

**Comment by majacal** [comment]
japp die rechte mit dem spaceinvader user der im code liegt acc sollten 
nur auf der highscore tabelle liegen und nicht auf der spaceinvaders db ...

aber ich denke wir sollten einfach nen publickey als credential 
hinterlegen ... das waere das sicherste

https://dev.mysql.com/doc/mysql-security-excerpt/5.6/en/sha256-authentication-plugin.html

also aehnlich wie ssh

public key und private key


der mysql server kann auch noch kein  ssl koennen


ich fuchs mich da mal rein ... alles nach und nach


Am 23.12.2016 um 17:16 schrieb aspecialkey:
